spring:
  application:
    name: gateway
  cloud:
    consul:
      host: 192.168.123.232
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名称小写
      routes:
  redis:
    host: 192.168.123.232

