spring:
  application:
    name: base-gateway
  cloud:
    consul:
      host: 192.168.123.232
      port: 8600
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名称小写
      routes:
  redis:
    host: 39.98.170.255
    password: cZmx8

