spring:
  application:
    name: base-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名称小写
      routes:
  redis:
    host: localhost
logging:
  config: classpath:logback.xml