spring:
  application:
    name: base-admin
  cloud:
    consul:
      host: 192.168.123.232
      port: 8600
      discovery:
        hostname: 192.168.123.19
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/base?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
        enabled: true
## DEV liquibase & H2
  liquibase:
    change-log: classpath:liquibase/master.yml
    enabled: false
    drop-first: false
  redis:
    host: localhost
server:
  port: 8094
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 开启sql日志
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
